"""AddByteaImages

Revision ID: 796e79739496
Revises: 0a5bad7c9ddb
Create Date: 2026-06-20 21:04:50.449224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796e79739496'
down_revision: Union[str, None] = '0a5bad7c9ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('imagen_data', sa.LargeBinary(), nullable=True))
    op.add_column('clientes', sa.Column('imagen_tipo', sa.String(length=40), nullable=True))
    op.drop_column('clientes', 'logo_url')
    op.add_column('equipo', sa.Column('imagen_data', sa.LargeBinary(), nullable=True))
    op.add_column('equipo', sa.Column('imagen_tipo', sa.String(length=40), nullable=True))
    op.drop_column('equipo', 'foto_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipo', sa.Column('foto_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('equipo', 'imagen_tipo')
    op.drop_column('equipo', 'imagen_data')
    op.add_column('clientes', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'imagen_tipo')
    op.drop_column('clientes', 'imagen_data')
    # ### end Alembic commands ###
