"""AddBrandColors

Revision ID: ae450cc311f0
Revises: 796e79739496
Create Date: 2026-06-21 02:22:17.450651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae450cc311f0'
down_revision: Union[str, None] = '796e79739496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('color_primario', sa.String(length=7), nullable=True))
    op.add_column('clientes', sa.Column('color_secundario', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'color_secundario')
    op.drop_column('clientes', 'color_primario')
    # ### end Alembic commands ###
