"""ChangeUsernameToEmail

Revision ID: e8bf45c613cd
Revises: cf2a917dca4f
Create Date: 2026-06-26 18:07:29.569736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8bf45c613cd'
down_revision: Union[str, None] = 'cf2a917dca4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM usuarios")
    op.add_column('usuarios', sa.Column('email', sa.String(length=255), nullable=False))
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=True)
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
